### ISSUE TITLE
Help with nifti files

### ISSUE THREAD

**Issue by haarisr** [eigenvivek/DiffDRR#172] opened 2023-12-05 19:40 UTC
Hi,

I am having troubles loading a nifti file for DRR generation. I get a very blurred image (not sure if its blurred). I have attached the image as well as the code used to generate the drr

```python3
deep_volume = nib.load(file_path)
volume = deep_volume.get_fdata()
spacing = deep_volume.header.get_zooms()


# Initialize the DRR module for generating synthetic X-rays
device = "cuda" if torch.cuda.is_available() else "cpu"
drr = DRR(
    volume,  # The CT volume as a numpy array
    spacing,  # Voxel dimensions of the CT
    sdr=300.0,  # Source-to-detector radius (half of the source-to-detector distance)
    patch_size=256,
    height=1024,  # Height of the detector in pixels
    delx=0.1,  # Pixel size in the detector plane
).to(device)

# Set the camera pose with rotation (yaw, pitch, roll) and translation (x, y, z)
rotation = torch.tensor(
    [
        [0.0, -0.0, -1.0],
        [1.0, 0.0, 0.0],
        [0.0, -1.0, 0.0],
    ],
    device=device,
).reshape(1, 3, 3)
bx, by, bz = torch.tensor(volume.shape) * torch.tensor(spacing) / 2
translation = torch.tensor([bx, by, bz], device=device).reshape(1, 3)


# 📸 Also note that DiffDRR can take many representations of SO(3) 📸
# For example, quaternions, rotation matrix, axis-angle, etc...
img = drr(
    rotation, translation, parameterization="matrix", bone_attenuation_multiplier=0
)
img = img.squeeze().cpu().numpy()
plt.imshow(img, cmap="gray")
plt.show()
camera, detector, texture = img_to_mesh(
    drr,
    rotation,
    translation,
    parameterization="matrix",
)
mesh = drr_to_mesh(drr)
plotter = pv.Plotter()
plotter.add_mesh(mesh, color="white", opacity=0.5)
plotter.add_mesh(camera, color="red", point_size=10)
plotter.add_mesh(detector, texture=texture)
plotter.show()

plot_drr(img, ticks=False)
plt.show()

```

![image](https://github.com/eigenvivek/DiffDRR/assets/122410226/ba2a10cf-4490-43aa-a412-b4687f40c6f6)

This is the preview in 3d. 

![image](https://github.com/eigenvivek/DiffDRR/assets/122410226/7441e282-9f8b-456c-8443-ce12b2ef67b3)

**Comment by haarisr** [comment] 2023-12-06 23:55
> Maybe also take a look at how NIFTI files are read in DeepDRR. They may have a better protocol for reading them than nibabel: 
They do use nibabel to read nifti files. I get the DRR generated using their tool.

How would you like me to send it? I can email it to you.

**Comment by haarisr** [comment] 2023-12-07 21:25
> It's very possible that I have a bug in exactly how I'm reading/storing the 3D volumes in the DRR.

I somehow believe that the initial CT transform is a necessary transform (i believe its SE3) to bring it to the same coordinate space before you generate the DRR. I'm not sure if I have to handle that or DiffDRR would. 

The nifit files store this transform in a header and DeepDRR use it as a `anatomical_from_ijk` where ijk is your volume voxel indices transform.

I could also be very wrong here.

**Comment by fedeface98** [comment] 2024-01-03 14:33
Hello,

Have you fixed the issue? The problem is in the loading of CT volume with nibabel or sitk?

Thanks a lot

**Comment by shenao1994** [comment] 2024-02-02 09:34
I suggest not using **SimpleITK** for now. If you use the **nibabel** to read images, you won't have this problem.

**Comment by eigenvivek** [comment] 2024-02-09 03:54
Hi @haarisr, if you have time, could you please install the latest version and try the `trilinear` interpolation backend? It should hopefully fix the majority of your aliasing issue!

It'll be something like
```python
drr = DRR(..., renderer="trilinear")
drr(..., n_points=250)
```

**Comment by haarisr** [comment] 2024-02-09 15:30
Initial testing looks like it works really well. Need to test a bit more but yes I see a usable drr now on both nifti and dicom. Will upload screenshots as I get to test more by next week. 

Great work!

**Comment by eigenvivek** [comment] 2024-02-09 16:29
fantastic!!!

**Comment by eigenvivek** [comment] 2024-02-19 14:57
Closing with #186. Feel free to reopen if issues persist!

**Closed** 2024-02-19 14:57 UTC
